(function(){
 'use strict';
 const el=id=>document.getElementById(id),h=esc;
 let data={status:{},coupons:[]},pending=null,lastFetch=0,loaded=false;
 const labels={won:'Trafiony',lost:'Nietrafiony',open:'Oczekujący'};
 el('aiCoupons').innerHTML=`<div class="ai-heading"><div><span class="ai-eyebrow">ANALIZA DANYCH MECZOWYCH</span><h1>Kupony AI</h1><p>Automatyczne tworzenie i sprawdzanie wyników na serwerze.</p></div><div class="ai-target">Preferowany kurs<strong>3–6</strong><small>Zakres 2–15 · single i AKO</small></div></div><article class="panel"><p id="sportsStatus" role="status">Pobieram stan analizy i wyników…</p><p id="sportsCoverage"></p><div class="tool-actions"><button id="sportsRefresh">↻ Odśwież wynik serwera</button><button id="sportsExport">Eksport historii</button></div><div id="sportsSetup" hidden><b>Analiza AI czeka na konfigurację</b><p>Dodaj klucz Gemini jako sekret <code>GEMINI_API_KEY</code> w repozytorium GitHub. Klucz pozostaje na serwerze — nie wpisuj go na stronie. Do tego czasu kupony AI nie są generowane.</p><a href="https://github.com/xlvlcl/arbi/settings/secrets/actions" target="_blank" rel="noopener">Otwórz sekrety repozytorium ↗</a></div></article><div class="ai-explanation"><b>Co trafia do AI?</b> Historia do 12 zakończonych meczów każdej drużyny: wyniki, gole, rywale oraz dom/wyjazd. Model nie dostaje kursów. Kursy służą dopiero do zestawienia dostępnego kuponu w wybranym przedziale. Procent jest subiektywną oceną AI, której trafność nie została jeszcze zweryfikowana — nie jest gwarancją ani wynikiem przeliczenia kursu.</div><div class="ai-list-heading"><h2>Gotowe kupony</h2><label>Widok<select id="sportsFilter"><option value="all">Wszystkie</option><option value="open">Oczekujące</option><option value="won">Trafione</option><option value="lost">Nietrafione</option></select></label></div><p class="tool-note">Wyniki są odczytywane z OpenLigaDB podczas uruchomień skanera. Zielony i czerwony licznik dotyczy trafności typów według wyników sportowych, nie rozliczenia zakładu na koncie bukmacherskim. Brak końcowego wyniku pozostawia typ oczekujący.</p><div id="sportsCards" class="ai-cards"></div><p id="sportsActionStatus" role="status"></p><details class="panel" style="margin-top:20px"><summary>Zakres danych i wcześniejsze zapisy</summary><p>Obsługiwane obecnie: 1., 2. i 3. liga niemiecka, rynki 1X2, suma goli 1.5/2.5/3.5 i obie drużyny strzelą. Brak danych o składach, kontuzjach, sędzim, pogodzie, rożnych, kartkach i faulach — AI nie analizuje tych informacji.</p><p>Poprzednie kupony lokalne oparte na kursach nie są wliczane do nowej historii AI.</p><button id="sportsExportLegacy">Eksport wcześniejszych kuponów z tej przeglądarki</button><p>Dane sportowe: <a href="https://www.openligadb.de/" target="_blank" rel="noopener">OpenLigaDB</a> · <a href="https://www.openligadb.de/lizenz" target="_blank" rel="noopener">licencja ODbL</a>. Dane społecznościowe mogą pojawić się z opóźnieniem lub zostać skorygowane.</p></details><dialog id="sportsDialog" class="ai-dialog"><button id="sportsClose" class="close" aria-label="Zamknij">×</button><div id="sportsDialogBody"></div></dialog>`;
 function counters(){const c={won:0,lost:0,open:0};for(const x of data.coupons)c[x.state in c?x.state:'open']++;return c}
 function render(){
  const count=counters(),status=data.status;el('aiScoreboard').innerHTML=`<span class="ai-score-label"><a href="#aiCoupons" class="ai-open-tab">✨ Otwórz Kupony AI →</a><small>Wspólna historia · wyniki z OpenLigaDB</small></span><span class="ai-score ai-win">✓ <b>${loaded?count.won:'—'}</b> trafione</span><span class="ai-score ai-loss">✕ <b>${loaded?count.lost:'—'}</b> nietrafione</span><span class="ai-score">◷ <b>${loaded?count.open:'—'}</b> oczekujące</span>`;
  const age=Date.now()/1000-Number(status.checked_at||0);el('sportsSetup').hidden=status.ai!=='not_configured';el('sportsStatus').textContent=loaded?(age>1800?'Aktualizacja jest opóźniona. ':'')+(status.message||'')+' Ostatnie sprawdzenie: '+date(status.checked_at)+'.':'Pobieram stan analizy i wyników…';el('sportsCoverage').textContent=loaded?`Dane wynikowe: ${status.results==='ok'?'pobrane':status.results==='partial'?'częściowe':'niedostępne'}. Dopasowane nadchodzące mecze z historią: ${Number(status.matched_events||0)}. Model: ${status.model||'—'}.`:'';
  const filter=el('sportsFilter').value||'all';const list=[...data.coupons].reverse().filter(c=>filter==='all'||c.state===filter);
  el('sportsCards').innerHTML=list.map(c=>`<article class="ai-ticket"><div class="ai-ticket-head"><span class="ai-state ai-${h(c.state)}">${labels[c.state]||'Oczekujący'}</span><button class="ai-info" data-sports-info="${h(c.id)}" aria-label="Analiza kuponu">ⓘ</button></div><div class="ai-odds"><span>Kurs z chwili zapisu<strong>${money(c.odds)}</strong></span><span class="ai-band">${c.legs.length>1?'AKO · '+c.legs.length+' typy':'Singiel'}</span></div><p>${h(c.bookmaker)} · ${date(c.created_at)}</p><ol class="ai-legs">${c.legs.map(l=>`<li><b>${h(l.event)}</b><span>${h(l.market)} · kurs ${money(l.odds)}</span><small>${date(l.starts_at)} · ${l.result?'wynik '+h(l.result.score.join(':'))+' · '+(l.result.won?'trafiony':'nietrafiony'):'oczekuje na wynik'}</small></li>`).join('')}</ol><div class="ai-estimate"><span>${c.legs.length>1?'Iloczyn ocen AI przy niezależności':'Ocena AI'}</span><b>${money(c.probability*100)}%</b></div><p class="ai-footnote">Ocena nieskalibrowana. Kursy mogły się zmienić. ${c.state==='open'?'Wynik sprawdzany automatycznie.':'Rozliczenie sportowe: '+date(c.settled_at)+'.'}</p><div class="tool-actions"><button class="primary" data-sports-copy="${h(c.id)}">Kopiuj kupon</button><button data-sports-info="${h(c.id)}">Pełna analiza</button></div></article>`).join('')||`<div class="empty"><h2>${loaded&&status.ai==='not_configured'?'AI nie jest jeszcze podłączone':'Brak gotowych kuponów w tym widoku'}</h2><p>${loaded&&status.ai==='not_configured'?'Dodanie sekretu GEMINI_API_KEY uruchomi analizę przy kolejnym skanie.':'Kupony pojawią się automatycznie po udanej analizie meczów z dostępnymi kursami. Nie trzeba wpisywać typów.'}</p></div>`;
 }
 function valid(d){return d?.version==='AI-SPORTS-1'&&Number.isFinite(d.status?.checked_at)&&Array.isArray(d.coupons)&&d.coupons.every(c=>typeof c.id==='string'&&Array.isArray(c.legs)&&c.legs.length&&['open','won','lost'].includes(c.state))}
 function load(force=false){if(pending)return pending;if(!force&&Date.now()-lastFetch<60000)return Promise.resolve();lastFetch=Date.now();pending=(async()=>{let successes=0;const urls=['data/ai-coupons.json','https://raw.githubusercontent.com/'+(config.repository||'xlvlcl/arbi')+'/main/fresh/web/data/ai-coupons.json'];await Promise.allSettled(urls.map(async url=>{const next=await getJSON(url);if(!valid(next))throw Error('format');successes++;if(Number(next.status.checked_at)>=Number(data.status.checked_at||0)){data=next;loaded=true;render()}}));if(!successes)el('sportsStatus').textContent='Nie udało się pobrać historii z serwera. '+(loaded?'Wyświetlone wyniki pochodzą z ostatniego odczytu.':'Nie można jeszcze potwierdzić liczników.');})().finally(()=>{pending=null});return pending}
 function analysis(c){el('sportsDialogBody').innerHTML=`<span class="ai-eyebrow">ANALIZA AI BEZ KURSÓW</span><h2>${h(c.bookmaker)} · kurs ${money(c.odds)}</h2><p>${c.legs.length>1?'Łączny procent to iloczyn ocen AI przy założeniu niezależności meczów. Nie jest niezależną analizą całego AKO.':'Procent to subiektywna ocena modelu.'} Skuteczność tych procentów nie została potwierdzona testami historycznymi.</p>${c.legs.map((l,i)=>`<section class="ai-analysis-leg"><h3>${i+1}. ${h(l.event)}</h3><p>${h(l.market)} · ocena AI ${money(l.probability*100)}% · model ${h(l.model)}</p><p class="ai-analysis-text">${h(l.analysis)}</p><p><b>Ryzyka wskazane przez model:</b> ${h(l.risks)}</p><p><b>Brakujące dane:</b> ${h((l.context?.missing||[]).join(', '))}.</p><details><summary>Dane przekazane AI — wyniki obu drużyn</summary>${['home_history','away_history'].map((key,j)=>`<h4>${h(j?l.context.away:l.context.home)}</h4><ul>${(l.context?.[key]||[]).map(m=>`<li>${h(date(m.date))} · ${h(m.home)} – ${h(m.away)} ${h(m.score.join(':'))} · <a href="${h(safeURL(m.source))}" target="_blank" rel="noopener">źródło</a></li>`).join('')}</ul>`).join('')}</details><p>${l.result?`Końcowy wynik: <b>${h(l.result.score.join(':'))}</b>. Typ ${l.result.won?'trafiony':'nietrafiony'}. Odczyt ${date(l.result.checked_at)}.`:'Brak końcowego wyniku — typ pozostaje oczekujący.'} <a href="${h(safeURL(l.source_url))}" target="_blank" rel="noopener">Wynik w źródle ↗</a></p></section>`).join('')}<p>Źródło danych: OpenLigaDB (ODbL). AI może błędnie interpretować dane; analiza nie obejmuje informacji, których nie pobrano.</p>`;el('sportsDialog').showModal()}
 function copyText(c){return ['KUPON • '+c.bookmaker,'Kurs z chwili zapisu: '+money(c.odds),...c.legs.map((l,i)=>(i+1)+'. '+l.event+' | '+l.market+' | kurs '+money(l.odds)+' | '+date(l.starts_at)),'Ocena AI bez kursów: '+money(c.probability*100)+'%'+(c.legs.length>1?' (iloczyn przy niezależności).':'.'),'Ocena nieskalibrowana, bez gwarancji. Sprawdź bieżące kursy i dostępność AKO.'].join('\n')}
 el('sportsCards').addEventListener('click',async event=>{const button=event.target.closest('[data-sports-copy],[data-sports-info]');if(!button)return;const c=data.coupons.find(x=>x.id===(button.dataset.sportsCopy||button.dataset.sportsInfo));if(!c)return;if(button.dataset.sportsInfo){analysis(c);return}const text=copyText(c);try{await navigator.clipboard.writeText(text);el('sportsActionStatus').textContent='Skopiowano gotowy kupon jako tekst.'}catch{el('sportsDialogBody').innerHTML='<h2>Kopiuj kupon</h2><textarea id="sportsCopyText" readonly style="width:100%;min-height:260px" aria-label="Gotowy kupon"></textarea>';el('sportsCopyText').value=text;el('sportsDialog').showModal();el('sportsCopyText').focus();el('sportsCopyText').select()}});
 function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 el('sportsExport').addEventListener('click',()=>download(data,'kupony-ai-historia.json'));el('sportsExportLegacy').addEventListener('click',()=>{try{download(JSON.parse(localStorage.getItem('arbi_ai_coupons_v1')||'[]'),'kupony-lokalne-archiwum.json')}catch{el('sportsActionStatus').textContent='Nie udało się odczytać poprzedniej historii.'}});
 el('sportsFilter').addEventListener('change',render);el('sportsClose').addEventListener('click',()=>el('sportsDialog').close());el('sportsRefresh').addEventListener('click',()=>load(true));window.updateAiCoupons=()=>load();setInterval(()=>{if(!el('app').hidden)load()},60000);render();load();
})();
