/* Independent local tools: no credentials, no external AI requests. */
(function(){
 'use strict';
 const el=id=>document.getElementById(id), h=esc;
 const read=(key,fallback)=>{try{const v=JSON.parse(localStorage.getItem('arbi_tools_'+key));return Array.isArray(v)?v:fallback}catch{return fallback}};
 let legs=read('draft',[]).slice(0,20),journal=read('journal',[]).slice(0,500),presets=read('presets',[]).slice(0,12);
 const persist=(key,value)=>{try{localStorage.setItem('arbi_tools_'+key,JSON.stringify(value));return true}catch{notice('Nie udało się zapisać danych. Pamięć przeglądarki jest niedostępna lub pełna.');return false}};
 function notice(text){el('toolsNotice').textContent=text}
 const field=(id,label,value,type='number',extra='')=>`<label>${h(label)}<input id="${id}" type="${type}" value="${h(value)}" ${extra}></label>`;
 const costFields=prefix=>field(prefix+'Stake','Stawka, zł',50,'number','min="0.01" max="100000" step="0.01"')+field(prefix+'Tax','Podatek od stawki, %',12,'number','min="0" max="99" step="0.01"')+field(prefix+'WinTax','Podatek od wygranej, %',10,'number','min="0" max="99" step="0.01"')+field(prefix+'Threshold','Próg podatku od wygranej, zł',2280,'number','min="0" step="0.01"');
 const costs=prefix=>['Stake','Tax','WinTax','Threshold'].map(x=>el(prefix+x).value);
 const calculate=(items,prefix)=>ArbiTools.analyze(items,...costs(prefix));
 el('assistant').innerHTML=`<div class="section-title"><div><h1>Asystent kuponów</h1><p>Zbuduj kupon i sprawdź koszty, zależności oraz założenia.</p></div></div><article class="panel"><p class="tool-note">Analizator matematyczny — bez podłączonego modelu AI. Nie analizuje statystyk drużyn, sędziego ani składów. Możesz wpisać dowolny rynek: rożne, kartki, faule, gole. Brak danych oznacza brak oceny szans, a nie automatyczne 80–100%.</p><div class="tool-actions"><button id="addLeg">+ Dodaj typ</button><button id="suggestLegs">Wczytaj do 3 pozycji Valuebet</button><button id="clearLegs">Wyczyść kupon</button></div><p id="suggestInfo" role="status"></p><div id="couponLegs"></div><div class="tool-form">${costFields('coupon')}</div><p class="tool-note">Koszty to edytowalne założenia kalkulatora. Sprawdź zasady konkretnego kuponu i promocji. Mnożenie kursów dotyczy zwykłego AKO; kurs Bet Builder wpisz jako jedną pozycję.</p><div id="couponResult" class="tool-result" aria-live="polite"></div><div class="tool-form">${field('couponName','Nazwa zapisu','Mój kupon','text','maxlength="100"')}</div><div class="tool-actions"><button id="saveCoupon">Zapisz w dzienniku</button><button id="copyCoupon">Kopiuj podsumowanie</button></div></article>`;
 el('toolbox').innerHTML=`<div class="section-title"><div><h1>Twój warsztat</h1><p>Ustawienia i zapisy są przechowywane tylko w tej przeglądarce. Eksportuj dziennik, aby zachować kopię.</p></div></div><div class="tools-grid"><article class="panel"><h2>1. Zapisane filtry</h2><p>Zapisz budżet, sport, szukaną frazę oraz progi Surebet, Radar i Valuebet.</p><div class="tool-form">${field('presetName','Nazwa zestawu','Moje filtry','text','maxlength="60"')}</div><button id="savePreset">Zapisz bieżące filtry</button><div id="presets" class="tool-actions"></div></article><article class="panel"><h2>2. Porównanie ofert po kosztach</h2><p>Porównuj ten sam typ i identyczne zasady rozliczenia.</p><div class="tool-form">${field('compareOddsA','Kurs A',2,'number','step="0.01" min="1.01"')}${field('compareTaxA','Podatek od stawki A, %',12,'number','min="0" max="99"')}${field('compareOddsB','Kurs B',1.85,'number','step="0.01" min="1.01"')}${field('compareTaxB','Podatek od stawki B, %',0,'number','min="0" max="99"')}${field('compareStake','Stawka, zł',50,'number','step="0.01" min="0.01"')}${field('compareWinTax','Podatek od wygranej, %',10)}${field('compareThreshold','Próg podatku od wygranej, zł',2280)}</div><div id="compareResult" class="tool-result" aria-live="polite"></div></article><article class="panel"><h2>3. Co jeśli kurs spadnie?</h2><p>Sprawdź zmianę wypłaty i próg opłacalności pojedynczego typu.</p><div class="tool-form">${field('simOdds','Obecny kurs',2,'number','min="1.01" step="0.01"')}${field('simNewOdds','Nowy kurs',1.8,'number','min="1.01" step="0.01"')}${costFields('sim')}</div><div id="simResult" class="tool-result" aria-live="polite"></div></article><article class="panel"><h2>4. Zaangażowany budżet</h2><div class="tool-form">${field('walletLimit','Własny limit otwartych stawek, zł',pref('walletLimit',200),'number','min="0" step="0.01"')}</div><div id="walletResult" class="tool-result"></div><p class="tool-note">Obliczenia dotyczą wyłącznie kuponów wpisanych do dziennika. To nie jest saldo konta bukmacherskiego.</p></article><article class="panel"><h2>5. Sprawdź przed postawieniem</h2>${['Kurs nadal jest dostępny u bukmachera.','Rynek, linia i zasady rozliczenia są zgodne.','Podatek i warunki promocji pasują do mojego konta.','Stawka mieści się w moim limicie.','Sprawdziłem powiązania typów z tego samego meczu.'].map(t=>`<label class="tool-check"><input type="checkbox">${h(t)}</label>`).join('')}<p id="checkProgress" role="status">0 / 5 sprawdzonych</p><button id="resetChecks">Nowe sprawdzenie</button></article></div><article class="panel" style="margin-top:16px"><h2>6. Dziennik i eksport</h2><p>Oznacz wynik ręcznie. Wypłata dla wygranego kuponu pochodzi z zapisanego kalkulatora; zwroty częściowe i cash-out nie są obsługiwane.</p><button id="exportJournal">Eksport CSV</button><div id="journal" class="tool-table"></div></article>`;
 const status=document.createElement('p');status.id='toolsNotice';status.setAttribute('role','status');el('app').appendChild(status);
 function newLeg(){return {event:'',market:'',selection:'',odds:'',probability:'',source:'Ręcznie wpisany typ'}}
 function renderLegs(){
  el('couponLegs').innerHTML=legs.map((x,i)=>`<div class="coupon-leg"><b>Typ ${i+1}</b><div class="tool-form">${[['event','Wydarzenie','text'],['market','Rynek / linia','text'],['selection','Typ','text'],['odds','Kurs','number'],['probability','Opcjonalna własna ocena szans, %','number']].map(([key,label,type])=>`<label>${h(label)}<input data-leg="${i}" data-key="${key}" type="${type}" value="${h(x[key])}" ${type==='number'?'step="0.01" min="0" max="1000"':'maxlength="160"'}></label>`).join('')}</div><small>${h(x.source||'Ręcznie wpisany typ')}</small><button data-remove="${i}" style="margin-left:12px">Usuń typ ${i+1}</button></div>`).join('')||'<p>Dodaj typ ręcznie lub wczytaj dostępne pozycje Valuebet.</p>';
  updateCoupon();
 }
 function updateCoupon(){
  const result=calculate(legs,'coupon');el('saveCoupon').disabled=!result;el('copyCoupon').disabled=!result;
  if(!result){el('couponResult').textContent='Wypełnij wydarzenie, rynek, typ i kurs powyżej 1 dla każdej pozycji. Stawka musi być dodatnia, a podatki od 0 do 99%.';return}
  const p=result.probability;
  el('couponResult').innerHTML=`<b>Kurs łączny: ${money(result.odds)}</b><br>Wypłata przy wygranej: ${money(result.payout)} zł · wynik: ${money(result.profit)} zł<br>Przy przegranej całego kuponu: −${money(el('couponStake').value)} zł<br>Próg rentowności: ${result.breakEven===null?'nieosiągalny':money(result.breakEven*100)+'%'}<br>Odwrotność kursu: ${money(result.implied*100)}% — to nie prognoza skuteczności.<br>${result.correlated?'<span class="tool-alert">Powtarza się wydarzenie. Typy mogą być zależne — nie wyliczamy łącznej szansy. Sprawdź też, czy bukmacher pozwala je łączyć.</span>':p===null?'Szansa wejścia: brak pełnych danych. Własne oceny muszą być większe od 0 i mniejsze od 100%.':`Iloczyn podanych ocen: ${money(p*100)}% przy założeniu niezależności typów.<br>Wartość oczekiwana przy tych założeniach: ${money(result.ev)} zł. To nie wynik modelu AI ani gwarancja.`}`;
 }
 el('couponLegs').addEventListener('input',event=>{const t=event.target;if(t.dataset.leg===undefined)return;const item=legs[Number(t.dataset.leg)];if(!item)return;item[t.dataset.key]=t.value;if(['event','market','selection'].includes(t.dataset.key)){item.probability='';const probabilityInput=el('couponLegs').querySelector('[data-leg="'+t.dataset.leg+'"][data-key="probability"]');if(probabilityInput)probabilityInput.value='';}item.source='Edytowane ręcznie — sprawdź dane i ocenę szans';persist('draft',legs);updateCoupon()});
 el('couponLegs').addEventListener('click',event=>{if(event.target.dataset.remove===undefined)return;legs.splice(Number(event.target.dataset.remove),1);persist('draft',legs);renderLegs()});
 el('addLeg').addEventListener('click',()=>{if(legs.length>=20){notice('Limit to 20 pozycji.');return}legs.push(newLeg());persist('draft',legs);renderLegs()});
 el('clearLegs').addEventListener('click',()=>{legs=[];persist('draft',legs);renderLegs()});
 el('suggestLegs').addEventListener('click',()=>{
  const stamp=Number(payload.status.last_success_at||0);const age=Date.now()/1000-stamp;
  if(!['ok','partial'].includes(payload.status.state)||age<0||age>300){el('suggestInfo').textContent='Brak świeżego skanu. Wczytywanie propozycji jest wstrzymane.';return}
  const seen=new Set();const candidates=(payload.valuebets||[]).filter(x=>new Date(x.starts_at).getTime()>Date.now()&&Number(x.confirmed_at)>0&&Date.now()/1000-Number(x.confirmed_at)<=300&&Number(x.probability)>0&&Number(x.probability)<1&&Number(x.leg?.odds)>1).sort((a,b)=>Number(b.probability)-Number(a.probability)).filter(x=>{const key=String(x.event).trim().toLowerCase();if(seen.has(key))return false;seen.add(key);return true}).slice(0,3);
  if(!candidates.length){el('suggestInfo').textContent='W świeżym skanie brak odpowiednich pozycji Valuebet. Możesz wpisać własne typy.';return}
  legs=candidates.map(x=>({event:x.event,market:x.market,selection:x.leg.selection,odds:x.leg.odds,probability:(Number(x.probability)*100).toFixed(2),source:`Szacunek rynku Valuebet, ${Number(x.reference_books)||0} bukmacherów odniesienia; odczyt ${date(x.confirmed_at)}; oferta ${x.leg.bookmaker}.` }));persist('draft',legs);renderLegs();el('suggestInfo').textContent='Wczytano '+legs.length+' różnych wydarzeń. Oferty mogą pochodzić od różnych bukmacherów — nie oznacza to, że można je zagrać razem. Sprawdź dostępność kursów u jednego bukmachera. Ocena nie obejmuje statystyk meczowych.';
 });
 el('saveCoupon').addEventListener('click',()=>{const result=calculate(legs,'coupon');if(!result)return;if(journal.length>=500){notice('Dziennik ma 500 wpisów. Wyeksportuj i usuń niepotrzebne zapisy.');return}const entry={id:crypto.randomUUID(),created:new Date().toISOString(),name:el('couponName').value.trim().slice(0,100)||'Kupon',stake:Number(el('couponStake').value),payout:result.payout,state:'open',legs:structuredClone(legs)};const next=[entry,...journal];if(persist('journal',next)){journal=next;renderJournal();notice('Zapisano kupon lokalnie w dzienniku.')}});
 el('copyCoupon').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(legs.map(x=>`${x.event} | ${x.market} | ${x.selection} @ ${x.odds}`).join('\n')+'\n'+el('couponResult').innerText);notice('Skopiowano analizę kuponu.')}catch{notice('Przeglądarka nie udostępnia schowka. Zaznacz i skopiuj podsumowanie ręcznie.')}});
 function renderJournal(){el('journal').innerHTML=journal.length?'<table><thead><tr><th>Data / kupon</th><th>Stawka</th><th>Wypłata przy wygranej</th><th>Wynik</th><th>Akcja</th></tr></thead><tbody>'+journal.map(x=>`<tr><td>${h(date(x.created))}<br>${h(x.name)}<details><summary>Typy</summary>${(x.legs||[]).map(l=>`${h(l.event)} · ${h(l.market)} · ${h(l.selection)} @ ${h(l.odds)}`).join('<br>')}</details></td><td>${money(x.stake)} zł</td><td>${money(x.payout)} zł</td><td><select aria-label="Wynik kuponu ${h(x.name)}" data-result="${h(x.id)}">${[['open','Otwarty'],['won','Wygrany'],['lost','Przegrany'],['void','Zwrot']].map(([value,label])=>`<option value="${value}" ${x.state===value?'selected':''}>${label}</option>`).join('')}</select></td><td><button data-delete="${h(x.id)}">Usuń</button></td></tr>`).join('')+'</tbody></table>':'<p>Brak zapisanych kuponów. Zapisz pierwszy w Asystencie kuponów.</p>';renderWallet()}
 el('journal').addEventListener('change',event=>{const id=event.target.dataset.result;if(!id||!['open','won','lost','void'].includes(event.target.value))return;const next=journal.map(x=>x.id===id?{...x,state:event.target.value}:x);if(persist('journal',next)){journal=next;renderWallet()}});
 el('journal').addEventListener('click',event=>{const id=event.target.dataset.delete;if(!id)return;const next=journal.filter(x=>x.id!==id);if(persist('journal',next)){journal=next;renderJournal()}});
 el('exportJournal').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([ArbiTools.csv(journal)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='dziennik-kuponow.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
 function renderWallet(){const t=ArbiTools.totals(journal),limit=Number(el('walletLimit').value);el('walletResult').textContent=!Number.isFinite(limit)||limit<0?'Podaj limit co najmniej 0 zł.':`Otwarte stawki: ${money(t.exposure)} zł. ${t.exposure>limit?'Przekroczono limit o '+money(t.exposure-limit):'Do limitu pozostaje '+money(limit-t.exposure)} zł. Wynik rozliczonych: ${money(t.profit)} zł. ${t.settled?'ROI: '+money(t.profit/t.settled*100)+'%.':''}`;save('walletLimit',el('walletLimit').value)}
 el('walletLimit').addEventListener('input',renderWallet);
 const filterIds=['budget','minimum','sport','search','radarGap','valueMinimum'];
 function renderPresets(){el('presets').innerHTML=presets.map((x,i)=>`<span><button data-preset="${i}">${h(x.name)}</button> <button aria-label="Usuń zestaw ${h(x.name)}" data-remove-preset="${i}">×</button></span>`).join('')}
 el('savePreset').addEventListener('click',()=>{if(presets.length>=12){notice('Możesz zapisać 12 zestawów filtrów.');return}const next=[...presets,{name:el('presetName').value.trim()||'Filtry',values:Object.fromEntries(filterIds.map(id=>[id,el(id).value]))}];if(persist('presets',next)){presets=next;renderPresets();notice('Zapisano bieżące filtry.')}});
 el('presets').addEventListener('click',event=>{const t=event.target;if(t.dataset.preset!==undefined){const preset=presets[Number(t.dataset.preset)];filterIds.forEach(id=>{el(id).value=preset.values[id]??'';el(id).dispatchEvent(new Event(id==='sport'?'change':'input'))});notice('Zastosowano zestaw: '+preset.name)}else if(t.dataset.removePreset!==undefined){const next=presets.filter((_,i)=>i!==Number(t.dataset.removePreset));if(persist('presets',next)){presets=next;renderPresets()}}});
 const simple=odds=>[{event:'Porównanie',market:'Ten sam rynek',selection:'Ten sam typ',odds}];
 function compare(){const a=ArbiTools.analyze(simple(el('compareOddsA').value),el('compareStake').value,el('compareTaxA').value,el('compareWinTax').value,el('compareThreshold').value),b=ArbiTools.analyze(simple(el('compareOddsB').value),el('compareStake').value,el('compareTaxB').value,el('compareWinTax').value,el('compareThreshold').value);el('compareResult').textContent=!a||!b?'Sprawdź kursy, stawkę i koszty.':`Wypłata A: ${money(a.payout)} zł. Wypłata B: ${money(b.payout)} zł. ${a.payout===b.payout?'Oferty dają równą wypłatę.':'Wyższa wypłata: '+(a.payout>b.payout?'A':'B')+', różnica '+money(Math.abs(a.payout-b.payout))+' zł.'}`}
 function simulate(){const a=calculate(simple(el('simOdds').value),'sim'),b=calculate(simple(el('simNewOdds').value),'sim');el('simResult').textContent=!a||!b?'Sprawdź kursy, stawkę i koszty.':`Wypłata: ${money(a.payout)} → ${money(b.payout)} zł. Zmiana: ${money(b.payout-a.payout)} zł. Nowy próg rentowności: ${b.breakEven===null?'nieosiągalny':money(b.breakEven*100)+'%'}. To wymagana skuteczność, nie prognoza.`}
 document.querySelectorAll('#assistant input').forEach(input=>{if(!input.dataset.leg)input.addEventListener('input',updateCoupon)});
 document.querySelectorAll('#toolbox input').forEach(input=>input.addEventListener('input',()=>{compare();simulate()}));
 const checks=[...document.querySelectorAll('.tool-check input')];const updateChecks=()=>{el('checkProgress').textContent=checks.filter(x=>x.checked).length+' / 5 sprawdzonych'};checks.forEach(x=>x.addEventListener('change',updateChecks));el('resetChecks').addEventListener('click',()=>{checks.forEach(x=>x.checked=false);updateChecks()});
 renderLegs();renderPresets();renderJournal();compare();simulate();
})();
