const fs=require('node:fs');const vm=require('node:vm');const assert=require('node:assert/strict');const path=require('node:path');const {webcrypto}=require('node:crypto');
const html=fs.readFileSync(path.join(__dirname,'../web/index.html'),'utf8');
const source=fs.readFileSync(path.join(__dirname,'../web/app.js'),'utf8');
const sample=JSON.parse(fs.readFileSync(path.join(__dirname,'web_fixture.json'),'utf8'));
let current=structuredClone(sample);let clock=2000000010000;
class TestDate extends Date{static now(){return clock}}
class Element{constructor(){this.hidden=false;this.style={};this.value='';this.dataset={};this.handlers={};this.classList={toggle(){}}}addEventListener(type,handler){this.handlers[type]=handler}showModal(){}close(){}}
const ids=new Map([...html.matchAll(/id="([^"]+)"/g)].map(x=>[x[1],new Element()]));
ids.get('radarGap').value='30';ids.get('valueMinimum').value='5';ids.get('app').hidden=true;ids.get('gate').hidden=false;
const views=['surebets','radar','valuebets','catalogue','notifications'].map(name=>{const e=new Element();e.dataset.view=name;return e});
const help=['calculation','coverage','tax','radar','value'].map(name=>{const e=new Element();e.dataset.help=name;return e});
const storage=new Map([['arbi_new_access','hash']]);
const document={getElementById:id=>{assert(ids.has(id),'Missing real element '+id);return ids.get(id)},querySelectorAll:selector=>selector==='[data-view]'?views:help,createElement:()=>new Element(),head:{appendChild(){}}};
const context={document,window:{},crypto:webcrypto,TextEncoder,URL,Intl,Date:TestDate,console,Math,JSON,Number,String,Boolean,Array,Promise,Error,AbortController,location:{href:'https://example.com/arbi/',reload(){}},setTimeout:(fn,delay)=>setTimeout(fn,Math.min(delay,40)),clearTimeout,setInterval(){},localStorage:{getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,value)},ArbiMath:require('../web/calculator.js')};
context.fetch=async(url)=>({ok:true,json:async()=>url.startsWith('config.json')?{password_hash:'hash',repository:'',onesignal_app_id:''}:structuredClone(current)});
vm.createContext(context);vm.runInContext(source,context);
(async()=>{
 await new Promise(r=>setTimeout(r,10));
 assert.equal(ids.get('app').hidden,false);
 assert.equal(ids.get('count').textContent,1);
 assert(ids.get('opportunities').innerHTML.includes('A - B'));
 assert.equal(ids.get('coverage').textContent,'1 / 1');
 assert.equal(ids.get('radarCount').textContent,1);assert.equal(ids.get('valueCount').textContent,1);
 assert(ids.get('valueList').innerHTML.includes('Target'));
 views.find(x=>x.dataset.view==='radar').handlers.click();assert.equal(ids.get('radar').hidden,false);assert.equal(ids.get('surebets').hidden,true);
 views.find(x=>x.dataset.view==='valuebets').handlers.click();assert.equal(ids.get('valuebets').hidden,false);assert.equal(ids.get('radar').hidden,true);
 ids.get('valueMinimum').value='10';ids.get('valueMinimum').handlers.input();assert.equal(ids.get('valueCount').textContent,0);
 ids.get('valueMinimum').value='5';ids.get('valueMinimum').handlers.input();assert.equal(ids.get('valueCount').textContent,1);
 ids.get('radarGap').value='1';ids.get('radarGap').handlers.input();assert.equal(ids.get('radarCount').textContent,0);
 ids.get('radarGap').value='30';ids.get('radarGap').handlers.input();assert.equal(ids.get('radarCount').textContent,1);
 ids.get('minimum').value='15';ids.get('minimum').handlers.input();assert.equal(ids.get('count').textContent,0);
 ids.get('minimum').value='.35';ids.get('minimum').handlers.input();assert.equal(ids.get('count').textContent,1);
 ids.get('search').value='Missing team';ids.get('search').handlers.input();assert.equal(ids.get('count').textContent,0);
 ids.get('search').value='';ids.get('search').handlers.input();
 current.status={...current.status,state:'error',attempt_at:2000000020,message:'Source unavailable'};
 await vm.runInContext('load()',context);
 assert.equal(ids.get('status').textContent,'Błąd odczytu');assert.equal(ids.get('count').textContent,0);
 assert(ids.get('diagnostic').textContent.includes('Source unavailable'));assert.equal(ids.get('radarCount').textContent,0);assert.equal(ids.get('valueCount').textContent,0);
 assert.equal(ids.get('last').textContent,new TestDate(2000000000000).toLocaleString('pl-PL',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}));
 current.status.attempt_at=2000000025;current.status.message='HTTP Error 403: Forbidden';await vm.runInContext('load()',context);
 assert(ids.get('diagnostic').textContent.includes('HTTP 403'));assert(ids.get('radarList').innerHTML.includes('HTTP 403'));assert(ids.get('valueList').innerHTML.includes('HTTP 403'));
 current=structuredClone(sample);current.status.attempt_at=2000000030;
 vm.runInContext('config.repository="test/repo"',context);
 context.fetch=(url,{signal})=>new Promise((resolve,reject)=>{
  if(url.startsWith('https://raw'))signal.addEventListener('abort',()=>reject(new Error('timed out')));
  else resolve({ok:true,json:async()=>structuredClone(current)});
 });
 const pending=vm.runInContext('load()',context);
 await new Promise(r=>setTimeout(r,5));assert.equal(ids.get('count').textContent,1,'First working source must render immediately');
 assert.strictEqual(vm.runInContext('load()',context),pending,'One polling cycle at a time');await pending;
 vm.runInContext('config.data_url="https://reader.example/feed/latest"',context);
 current=structuredClone(sample);current.status.attempt_at=2000000040;
 let feedCalls=[];
 context.fetch=async(url,options)=>{
  feedCalls.push({url,options});assert(url.startsWith('https://reader.example'),'A fresh feed must not download GitHub snapshots');
  return {ok:true,status:200,headers:{get:()=> '"2000000040"'},json:async()=>structuredClone(current)};
 };
 await vm.runInContext('load()',context);assert.equal(feedCalls.length,1);assert.equal(ids.get('count').textContent,1);
 context.fetch=async(url,options)=>{
  assert.equal(options.headers['If-None-Match'],'"2000000040"');return {ok:false,status:304};
 };
 await vm.runInContext('load()',context);assert.equal(ids.get('count').textContent,1,'304 keeps previously fetched data');
 const newer=structuredClone(sample);newer.status.attempt_at=2000000050;
 const stale=structuredClone(sample);stale.status.attempt_at=1999999000;stale.status.last_success_at=1999999000;
 context.fetch=async url=>({ok:true,status:200,headers:{get:()=>''},json:async()=>structuredClone(url.startsWith('https://reader.example')?stale:newer)});
 await vm.runInContext('load()',context);assert.equal(vm.runInContext('payload.status.attempt_at',context),2000000050,'Stale feed must fall back to newer GitHub data');
 context.fetch=async url=>url.startsWith('https://reader.example')?{ok:false,status:503}:{ok:true,status:200,json:async()=>structuredClone(newer)};
 await vm.runInContext('load()',context);assert.equal(ids.get('count').textContent,1,'An unconfigured feed must preserve working fallbacks');
 context.navigator={userAgent:'iPhone',standalone:false};
 vm.runInContext('config.onesignal_app_id="test-app";pushStarted=false;initPush()',context);
 assert(ids.get('pushStatus').textContent.includes('Dodaj do ekranu początkowego'));
 assert.equal(ids.get('push').disabled,true,'An iPhone browser tab cannot wait forever for push');
 context.navigator.standalone=true;context.window.OneSignalDeferred=[];
 vm.runInContext('pushStarted=false;initPush()',context);
 assert.equal(ids.get('push').disabled,true,'Permission button stays disabled until SDK is ready');
 let changeListener;
 const sdk={init:async()=>{},Notifications:{permission:true,isPushSupported:()=>true,addEventListener(){}},User:{PushSubscription:{id:null,optedIn:false,addEventListener(type,fn){changeListener=fn},optIn:async()=>{}}}};
 await context.window.OneSignalDeferred[0](sdk);
 assert(ids.get('pushStatus').textContent.includes('Czekam na rejestrację'),'Permission alone is not a registered push device');
 sdk.User.PushSubscription.id='subscription';sdk.User.PushSubscription.optedIn=true;changeListener();
 assert(ids.get('pushStatus').textContent.includes('urządzenie jest zarejestrowane'));
 assert.equal(ids.get('push').disabled,true);
 context.window.OneSignalDeferred=[];vm.runInContext('pushStarted=false;initPush()',context);
 await context.window.OneSignalDeferred[0]({...sdk,init:async()=>{throw new Error('Site origin mismatch')}});
 assert(ids.get('pushStatus').textContent.includes('Site origin mismatch'),'SDK failure should remain visible');
 assert.equal(ids.get('push').textContent,'Odśwież obsługę push');
 console.log('Interfejs, odświeżanie danych oraz push: instalacja iPhone, rejestracja urządzenia i błędy SDK: OK.');
})().catch(error=>{console.error(error);process.exitCode=1});
